function(git_run out_var command)
    separate_arguments(cmd_list NATIVE_COMMAND "${command}")
    execute_process(
        COMMAND git ${cmd_list}
        WORKING_DIRECTORY "${SOURCE_DIR}"
        OUTPUT_VARIABLE result
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
    )
    set(${out_var} "${result}" PARENT_SCOPE)
endfunction()

git_run(CURRENT_BRANCH "branch --show-current")

if(CURRENT_BRANCH STREQUAL "master")
    git_run(MONIKA_BUILD_NUMBER "rev-list --count master")
else()
    git_run(MERGE_BASE "merge-base refs/remotes/origin/master HEAD")
    git_run(MASTER_COUNT "rev-list --count ${MERGE_BASE}")
    git_run(DIVERGE_COUNT "rev-list --count ${MERGE_BASE}..HEAD")

    set(MONIKA_BUILD_NUMBER "${MASTER_COUNT}+${DIVERGE_COUNT}")
endif()

# Git Properties
git_run(MONIKA_BUILD_TAG    "describe --broken --dirty --all")
git_run(MONIKA_BUILD_HASH   "rev-parse --short HEAD")
git_run(MONIKA_BUILD_ORIGIN "remote get-url origin")

# Timestamp Properties
string(TIMESTAMP MONIKA_TIMESTAMP  "%a %b %d %H:%M:%S UTC %Y" UTC)
string(TIMESTAMP MONIKA_BUILD_YEAR "%Y")

# Author Properties
if(NOT MONIKA_BUILD_AUTHOR)
    set(MONIKA_BUILD_AUTHOR "Trung Nguyen")
endif()

# Header Content
set(CONTENT "/* Auto-generated by CMake - do not edit */
#pragma once

#ifdef RC_INVOKED

// Do not quote properties for RC, they will be stringified later.

#define MONIKA_BUILD_NUMBER ${MONIKA_BUILD_NUMBER}
#define MONIKA_BUILD_TAG    ${MONIKA_BUILD_TAG}
#define MONIKA_BUILD_HASH   ${MONIKA_BUILD_HASH}
#define MONIKA_BUILD_ORIGIN ${MONIKA_BUILD_ORIGIN}
#define MONIKA_BUILD_YEAR   ${MONIKA_BUILD_YEAR}
#define MONIKA_BUILD_AUTHOR ${MONIKA_BUILD_AUTHOR}

#else

#define MONIKA_BUILD_NUMBER \"${MONIKA_BUILD_NUMBER}\"
#define MONIKA_BUILD_TAG    \"${MONIKA_BUILD_TAG}\"
#define MONIKA_BUILD_HASH   \"${MONIKA_BUILD_HASH}\"
#define MONIKA_BUILD_ORIGIN \"${MONIKA_BUILD_ORIGIN}\"
#define MONIKA_BUILD_YEAR   \"${MONIKA_BUILD_YEAR}\"
#define MONIKA_BUILD_AUTHOR \"${MONIKA_BUILD_AUTHOR}\"

#endif // RC_INVOKED
")

# Only write if content changed.
if(EXISTS "${OUTPUT_FILE}")
    file(READ "${OUTPUT_FILE}" OLD_CONTENT)
endif()

if(NOT "${CONTENT}" STREQUAL "${OLD_CONTENT}")
    file(WRITE "${OUTPUT_FILE}" "${CONTENT}")
endif()
